
      // list the words to each variables in arrays
      const twoLetters = ['ay: expression of agreement or approval',
  'ba: informal term for "bachelor of arts"',
  'be: to exist or occur',
  'bi: prefix meaning "two" or "twice"',
  'bo: slang term for a friend or companion',
  'by: near or beside',
  'ch: abbreviation for "chapter"',
  'da: informal term for "the"',
  'de: preposition meaning "of" or "from"',
  'in: located or situated within',
  'of: expressing the relationship between a part and a whole',
  'to: expressing motion or direction toward a point',
  'is: third-person singular present of the verb "be"',
  'it: used to refer to a thing previously mentioned or easily identified',
  'on: positioned or supported by',
  'no: opposite of "yes" or absence of something',
  'us: referring to the speaker and one or more other people',   'ay: expression of agreement or approval',
  'ba: informal term for "bachelor of arts"',
  'be: to exist or occur',
  'bi: prefix meaning "two" or "twice"',
  'bo: slang term for a friend or companion',
  'by: near or beside',
  'ch: abbreviation for "chapter"',
  'da: informal term for "the"',
  'de: preposition meaning "of" or "from"',
  'in: located or situated within',
  'of: expressing the relationship between a part and a whole',
  'to: expressing motion or direction toward a point',
  'is: third-person singular present of the verb "be"',
  'it: used to refer to a thing previously mentioned or easily identified',
  'on: positioned or supported by',
  'no: opposite of "yes" or absence of something',
  'us: referring to the speaker and one or more other people',

    'ha: an exclamation of surprise or realization',
  'hi: a greeting or expression of acknowledgment',
  'jo: a term used to refer to a person',
  'ka: a particle used to indicate a question or uncertainty',
  'ki: a term used to refer to an object or thing',
  'la: a musical note or tone',
  'li: a particle used to form adverbs from adjectives',
  'mi: a musical note or tone',
  'mm: a sound made to express satisfaction or pleasure',
  'mo: a term used to indicate similarity or comparison',
  'mu: a term used to indicate negation or absence',
  'na: a particle used to indicate possession or association',
  'ne: a particle used to seek confirmation or agreement',
  'yo: an exclamation used to get attention or emphasize a point'];

      const threeLetters = ['And: conjunction used to connect words or phrases',
  'Fix: to repair or mend something',
  "Own: to possess or have something as one's own",
  'Are: present tense form of the verb be',
  'Fly: to move through the air using wings or other means',
  'Odd: strange or unusual',
  'Ape: a primate resembling humans',
  'Fry: to cook food in hot oil or fat',
  'Our: belonging to or associated with us',
  'Ace: a playing card with a single spot',
  'Act: to perform a specific action',
  'Got: past tense form of the verb get',
  'Pet: a domesticated animal kept for companionship',
  'Ask: to inquire or request information',
  'Get: to receive or obtain something',
  'Peg: a small cylindrical or tapered piece used to fasten things together',
  'Arm: the upper limb of the human body'
,   'God: the supreme being or deity',
  'Paw: the foot of an animal, especially a quadruped',
  'Age: the length of time that a person has lived',
  'Ago: in the past; before now',
  'Gas: a substance in a state that expands to fill any container',
  'Pit: a large hole in the ground',
  'Air: the invisible gaseous substance surrounding the Earth',
  'Hat: a covering for the head',
  'Put: to place or set something in a particular position',
  'Ate: past tense form of the verb "eat"',
  'Hit: to strike or collide with something',
  'Pot: a round container used for cooking or storing food',
  'All: the whole quantity or extent of something',
  'But: used to introduce a contrasting or unexpected statement',
  'Pin: a thin piece of metal used to fasten things together',
  'Bye: a short form of "goodbye", used as a farewell',
  'Rat: a small rodent with a long tail and pointed snout',
  'Bad: not good; of poor quality',
  'Rag: a piece of old cloth used for cleaning or wiping',
  'Big: of considerable size, extent, or intensity',
  'Rub: to apply pressure and move something with a back-and-forth motion',
  'Bed: a piece of furniture used for sleeping or resting',
  'Row: a line of objects, people, or vehicles arranged side by side',
         'Boy: a male child or young man',
  'Run: to move swiftly on foot',
  'Bus: a large motor vehicle used for carrying passengers',
  'Saw: a cutting tool with a blade edged with teeth',
  'Bit: a small piece or quantity of something',
  'See: to perceive with the eyes',
  'Buy: to acquire in exchange for money',
  'Set: to put or place something in a particular position',
  'Bun: a small, round, sweet bread roll',
  'Sit: to rest with the weight supported by the buttocks',
  'Cub: a young animal, such as a lion or bear',
  'Sir: a respectful term used to address a man',
  'Cat: a small domesticated carnivorous mammal',
  'Sat: past tense form of the verb "sit"',
  'Car: a four-wheeled motor vehicle used for transportation',
  'Sob: to cry or make sounds of distress while crying',
  'Cut: to make an incision or divide something with a sharp tool',
  'Tap: to strike lightly or gently with a quick blow',
  'Cow: a large domesticated bovine animal',
  'Tip: the pointed or rounded end of something',
  'Cry: to shed tears as an expression of pain, distress, or emotion',
  'Top: the highest or uppermost part of something',
  'Can: a cylindrical container typically used for holding beverages',
  'Toe: one of the digits of the foot',
  "Dad: a person's father",
  'Tan: a light brown color',
  'Dab: to lightly touch or apply with quick, gentle movements',
  'Ten: the number equivalent to the product of two and five',
  'Dam: a barrier constructed to hold back water and create a reservoir',
  'Two: the number equivalent to the sum of one and one',
  'Dug: past tense form of the verb "dig"',
  'Use: to employ for a purpose',
  'Den: a small, comfortable room used for relaxation or privacy',
  'Van: a large enclosed motor vehicle used for transporting goods or people',
  'Dot: a small round mark or spot',
  'Vet: a veterinarian or veterinary surgeon',
  'Dip: to immerse briefly in a liquid',
  'Was: past tense form of the verb "be"',
  'Ear: the organ of hearing in humans and other vertebrates',
  'Wet: covered or saturated with water or another liquid',
          'Eat: to consume food',
  'Win: to be successful or victorious',
  'End: the final part or conclusion of something',
  'War: a state of armed conflict between nations or groups',
  'Elf: a mythical creature often depicted as a small, mischievous being',
  'Why: for what reason or purpose',
  'Egg: a hard-shelled reproductive body produced by birds and some reptiles',
  'Who: used to refer to a person or people to ask for information or inquire about identity',
  'Far: a long distance away',
  'Way: a method, style, or manner of doing something',
  'Fat: having an excessive amount of body weight',
  'Wow: used to express astonishment, admiration, or excitement',
  'Few: a small number of something',
  'You: used to refer to the person or people being addressed',
  'Fan: a device used to create a current of air',
  'Yes: an affirmative or positive response',
  'Fun: enjoyment, amusement, or lighthearted pleasure',
  'Yak: a large, long-haired wild ox found in the Himalayas',
  'Fit: in good physical condition',
  'Zip: to move quickly or energetically',
  'Old: having lived or existed for a long time',
  'Zap: to strike or hit with force',
  'Fin: a flattened appendage on the body of a fish',
  'Owl: a nocturnal bird of prey',
  'Fox: a carnivorous mammal with a pointed snout and bushy tail',
  'Not: used to express negation, denial, or refusal',
  'One: the number denoting a quantity of one',
  'Nut: a hard-shelled fruit or seed',
  'Oar: a long pole with a flat blade used for rowing a boat',
  'Out: away from the inside or center',
  'New: recently made, introduced, or discovered',
  'Won: past tense form of the verb "win"',
  'Net: a fabric consisting of connected strands',
  'May: used to express possibility or permission',
  "Nod: to move one's head up and down as a way of showing agreement or understanding",
  'Met: past tense form of the verb "meet"',
  'Now: at the present time',
  "Mum: a term used to refer to one's mother",
  'Mix: to combine different substances or ingredients',
          'Mom: a term used to refer to one\'s mother',
  'Mug: a cylindrical container with a handle, used for holding and drinking hot beverages',
  'Map: a diagrammatic representation of an area or a geographical region',
  'Mad: feeling or showing anger',
  'Man: an adult human male',
  'Nap: a short period of sleep, especially during the day',
  'Lot: a particular group, collection, or quantity of something',
  'Let: to allow or permit',
  'Lay: to put something down in a horizontal position',
  'Lit: past tense and past participle of the verb "light"',
  'Job: a paid position of regular employment',
  'Jar: a wide-mouthed cylindrical container with a lid',
  'Jug: a large container with a narrow mouth and a handle, used for holding liquids',
  'Jam: a sweet spread or preserve made from fruit and sugar',
  'Jab: to poke or thrust abruptly or sharply',
  'Ill: not in good health; sick or unwell',
  'Ice: frozen water',
  'Ink: a colored fluid or paste used for writing or printing',
  'Hen: a female chicken',
  'His: belonging to or associated with a male person or animal previously mentioned',
  'Her: belonging to or associated with a female person or animal previously mentioned',
  'Has: third-person singular present tense of the verb "have"',
  'How: in what way or manner',
  'Had: past tense and past participle of the verb "have"',
  'Gas: a substance in a physical state in which it expands and fills the space it is in',
  'Gel: a jelly-like substance',
  'God: a supreme being or deity',
  'Get: to obtain, acquire, or receive',
  'Fly: to move through the air using wings',
  'Fry: to cook food in hot fat or oil',
  'For: indicating the use or purpose of something',
  'Hat: a covering for the head, typically with a brim and a shaped crown',
  'Hit: to strike someone or something with force',
  'Hen: a female chicken',
  'Get: to obtain, acquire, or receive',
  'Gel: a jelly-like substance',
  'Gas: a substance in a physical state in which it expands and fills the space it is in',
  'God: a supreme being or deity',
  'Egg: a hard-shelled reproductive body produced by birds and some reptiles',
  'Eye: the organ of sight',
  'Ear: the organ of hearing',
  'End: the final part or conclusion of something',
  'Dug: past tense of the verb "dig"',
  'Den: a small, cozy room in a house where people can relax or pursue hobbies',
  'Dip: to lower or be lowered briefly',
  'Dot: a small round mark or spot',
  'Dam: a barrier constructed to hold back water and raise its level',
  'Day: a period of 24 hours',
  'Did: past tense of the verb "do"',
  'Dab: to touch or stroke lightly and gently',
         'Dad: a term used to refer to one\'s father',
  'Cut: to divide or separate something with a sharp tool or instrument',
  'Cab: a taxi or a vehicle used for transportation',
  'Cry: to shed tears as an expression of distress, pain, or sorrow',
  'Cow: a large domesticated ungulate mammal kept for its milk or meat',
  'Car: a road vehicle with four wheels and an internal combustion engine',
  'Cat: a small domesticated carnivorous mammal kept as a pet',
  'Cub: a young bear, lion, tiger, or other carnivorous mammal',
  'Buy: to acquire something in exchange for money',
  'Bit: a small piece or quantity of something',
  'Box: a container with a flat base and sides, typically square or rectangular',
  'Bag: a flexible container with an opening at the top',
  'But: used to introduce a phrase or clause contrasting with what has already been mentioned',
  'Bat: a specially shaped implement used for hitting the ball in various games',
  'Bad: of poor quality or low standard',
  'Bye: a shortened form of "goodbye," used to bid farewell',
  'Boy: a male child or young man',
  'Bed: a piece of furniture for sleeping or resting upon',
  'Big: of considerable size, extent, or intensity',
  'Ace: a playing card with a single spot on it, ranked as the highest card in its suit',
  'Ago: before the present or a specified time',
  'Age: the length of time that a person has lived or a thing has existed',
  'Arm: the upper limb of the human body, extending from the shoulder to the hand',
  'Ask: to inquire about or request information',
  'Act: to take action; do something',
  'Ate: past tense of the verb "eat"',
  'Air: the invisible gaseous substance surrounding the earth',
  'Pup: a young dog, especially one that is not yet fully grown',
  'Put: to place something in a particular position',
  'Pot: a round, deep container used for cooking or storing food',
  'Pop: to make a sudden, sharp, explosive sound',
  'Pin: a thin piece of metal with a sharp point at one end and a round head at the other',
  'Rat: a medium-sized rodent with a long tail',
  'Rag: a piece of old cloth, especially one torn from a larger piece',
  'Rub: to apply pressure and friction to something with a repeated back-and-forth motion',
  'Row: a line of things or people placed next to each other',
  'Run: to move swiftly on foot',
  'Rap: a genre of music characterized by rhythmic rhyming speech',
  'Ram: a male sheep',
  'See: to perceive with the eyes; observe',
  'Saw: a cutting tool with a thin blade and a handle',
  'Set: to put, lay, or stand something in a specified place or position',
  'Sit: to rest with the weight supported by the buttocks and the back in an upright position',
  'Sir: a respectful form of address used for a man',
  'Sat: past tense of the verb "sit"',
  'Sob: to cry noisily, making loud, convulsive gasps',
  'Tap: to strike lightly with a quick, sharp blow',
  'Tip: the pointed or rounded end or extrem', 'Top: the highest point or part of something',
  'Tug: to pull something with a sudden, sharp movement',
  'Toe: one of the digits of the foot'];

      const fourLetters = ['Also: in addition; too',
  'Able: having the skill or capability to do something',
  'Acid: a chemical substance with a sour taste and the ability to react with bases',
  'Aged: having reached a certain age; old',
  'Away: at a distance from a particular place',
  'Baby: a very young child',
  'Back: the rear surface of something',
  'Bank: a financial institution where money is deposited, borrowed, or exchanged',
  'Been: past participle of "be"; having existed or occurred in the past',
  'Ball: a round object used in various sports and games',
  'Base: the bottom or supporting part of something',
  'Busy: actively engaged in work or activity',
  'Bend: to curve or flex something',
  'Bell: a hollow instrument that makes a ringing sound when struck',
  'Bird: a warm-blooded vertebrate with feathers and beak',
  'Come: to move or travel toward a destination',
  'Came: past tense of "come"; arrived or appeared',
  'Calm: a state of tranquility or peacefulness',
        'Card: a rectangular piece of stiff paper used for various purposes',
  'Coat: a garment worn over other clothing for warmth or protection',
  'City: a large and permanent human settlement',
  'Chat: to engage in an informal conversation or talk',
  'Cash: money in the form of coins or banknotes',
  'Crow: a large, black bird with a harsh call',
  'Cook: to prepare food by applying heat',
  'Cool: having a moderately low temperature',
  'Dark: having little or no light; lacking brightness',
  'Each: every one of two or more people or things',
  'Evil: profoundly immoral or wicked',
  'Even: flat or level; having a consistent or equal extent',
  'Ever: at any time',
  'Face: the front part of the head, from the forehead to the chin',
  'Fact: a thing that is known or proved to be true',
  'Four: the number equivalent to the sum of two and two',
  'Five: the number equivalent to the sum of four and one',
  'Fair: treating people equally and without favoritism',
  'Feel: to perceive through touch or physical sensation',
  'Fell: past tense of "fall"; descended from a higher to a lower place',
  'Fool: a person who lacks good sense or judgment',
  'Fire: the state of combustion producing heat and light',
  'Fine: of high quality or excellence',
  'Fish: a limbless cold-blooded vertebrate that lives in water',
  'Game: an activity or sport with specific rules and goals',
  'Gone: no longer present or available',
  'Gold: a precious yellow metallic element',
  'Girl: a female child or young woman',
          'Have: to possess or own something',
  'Hair: the thin thread-like strands that grow on the head',
  'Here: in or at this place or position',
  'Hear: to perceive sound through the ears',
  'Into: expressing movement or action toward the inside of something',
  'Iron: a strong, hard, magnetic metallic element',
  'Jump: to propel oneself quickly upward off the ground',
  'Blow: to move or cause to move with force and speed',
  'Kick: to strike with the foot or feet',
  'Kill: to cause the death of a person, animal, or other living thing',
  'Life: the condition that distinguishes living organisms from non-living things',
  'Like: to find something enjoyable or agreeable',
  'Love: a deep affection or fondness for someone or something',
  'Main: most important or principal in rank, importance, or position',
  'Move: to change position or place',
  'Meet: to come into the presence or company of someone',
  'More: a greater or additional amount or quantity',
  'Nose: the part projecting above the mouth on the face',
  'Near: at or to a short distance away',
  'Open: to make or become open',
  'Only: and no one or nothing more besides',
  'Push: to exert force on someone or something in order to move it away from oneself',
  'Pull: to exert force in order to bring something toward oneself',
  'Sell: to exchange goods or services for money',
  'Sale: the exchange of goods or services for money',
  'Slim: thin in an attractive or elegant way',];
      
      const fiveLetters = [
         'About: on the subject of; concerning',
  'Alert: quick to notice and react to potential danger or opportunity',
  'Argue: to exchange or express diverging or opposite views in a heated or angry way',
  'Beach: a pebbly or sandy shore, especially by the ocean',
  'Above: at a higher level or layer than',
  'Alike: similar in nature; alike in appearance',
  'Arise: to emerge; become apparent',
  'Began: past tense of begin; started',
  'Abuse: cruel or violent treatment of someone',
  'Alive: living; not dead',
  'Array: an ordered arrangement or display',
  'Begin: to start; commence',
  'Actor: a person who performs in plays, movies, or television shows',
  'Allow: to give permission or consent',
  'Aside: to one side; out of the way',
  'Begun: past participle of begin; started',
  'Acute: having or showing a perceptive understanding or insight',
  'Alone: by oneself; without others',
  'Asset: a useful or valuable thing or person',
  'Being: the existence or nature of a person',
  'Admit: to confess or acknowledge',
  'Along: in a line parallel to; alongside',
  'Audio: relating to sound or the reproduction of sound',
  'Below: at a lower level or layer than',
          'Adopt: to take on or assume',
  'Alter: to change or modify',
  "Audit: an official inspection of an organization's accounts",
  'Bench: a long seat for several people',
  'Adult: a person who is fully grown or developed',
  'Among: surrounded by; in the company of',
  'Avoid: to keep away from; to evade',
  'Billy: a male goat',
  'After: following in time or place',
  'Anger: a strong feeling of displeasure',
  'Award: a prize or other mark of recognition',
  'Birth: the emergence of a baby or other young from the body of its mother',
  'Again: once more; another time',
  'Angle: the space between two lines or surfaces that meet',
  'Aware: having knowledge or perception',
  'Black: the darkest color',
  'Agent: a person who acts on behalf of another',
  'Angry: feeling or showing anger',
  'Badly: in an unsatisfactory, inadequate, or unsuccessful way',
  'Blame: to assign responsibility for a fault or wrong',
  'Ahead: in front; in advance',
  'Apple: a round fruit with crisp and juicy flesh',
  'Bases: the bottom supports of a structure',
  'Block: a large solid piece of hard material',
  'Alarm: a warning of danger or an emergency',
  'Apply: to make a formal application or request',
  'Basic: fundamental; essential',
  'Blood: the red liquid that circulates in the arteries and veins',
  'Album: a collection of recorded music',
  'Arena: a place where sports, concerts, or other events take place',
  'Basis: a fundamental principle or groundwork',
  'Board: a flat piece of material used for various purposes',
  'Boost: to increase or improve',
  'Buyer: a person who purchases goods or services',
  'China: a country in East Asia',
  'Cover: to place something over or upon',
         'Booth: a small enclosed space',
  'Cable: a thick strong rope',
  'Chose: past tense of "choose"',
  'Craft: a skill or profession',
  'Bound: tied or fastened',
  'Calif: abbreviation for California',
  'Civil: relating to citizens or the state',
  'Crash: a sudden loud noise',
  'Brain: the organ inside the head that controls thought',
  'Carry: to hold or support while moving',
  'Claim: to state that something is true',
  'Cream: a thick, yellowish-white liquid',
  'Brand: a type of product made by a particular company',
  'Catch: to capture or seize',
  'Class: a group of students taught together',
  'Crime: an action that is against the law',
  'Bread: a staple food made from flour and water',
  'Cause: a reason or motive',
  'Clean: free from dirt or pollution',
  'Cross: to go from one side to the other',
  'Break: to separate into pieces',
  'Chain: a series of connected links',
  'Clear: easy to perceive or understand',
  'Crowd: a large group of people',
  'Breed: a specific type or variety',
  'Chair: a piece of furniture for sitting on',
  'Click: a short, sharp sound',
  'Crown: a circular ornament worn on the head',
  'Brief: short in duration or extent',
  'Chart: a visual representation of data',
  'Clock: a device that measures and shows time',
  'Curve: a smoothly bending line',
  'Bring: to come with or accompany',
  'Chase: to pursue or run after',
  'Close: near or next to',
  'Cycle: a series of events that repeat in a particular order',
  'Broad: wide or spacious',
  'Cheap: low in cost or price',
  'Coach: a person who trains or instructs',
  'Daily: occurring every day',
  'Broke: past tense of "break"',
  'Check: to examine or verify',
  'Coast: the land next to the sea',
  'Dance: a series of rhythmic movements',
  'Brown: a color between red and yellow',
  'Chest: the front part of the body between the neck and the stomach',
  'Could: past tense of "can"',
  'Dated: marked with a particular date',
  'Build: to construct or create',
  'Chief: the leader or head of a group',
  'Count: to determine the total number of',
  'Dealt: past tense of "deal"',
  'Built: past tense of build',
  'Child: a young human being',
  'Court: a place where legal cases are heard',
  'Death: the permanent cessation of all vital functions',
  "Debut: a person's first appearance or performance",
  'Entry: a way to enter or access',
  'Forth: onward in time, place, or order',
  'Group: a collection of individuals',
  'Delay: to postpone or put off',
  'Equal: having the same quantity, value, or status',
  'Forty: the number equivalent to four times ten',
  'Grown: past participle of "grow"',
  'Depth: the distance from the top or surface to the bottom',
  'Error: a mistake or incorrect action',
  'Forum: a place for open discussion',
  'Guard: a person who protects or watches over',
  'Doing: the action of performing or carrying out',
  'Event: a planned or organized occasion',
  'Found: past tense of "find"',
  'Guess: to estimate or make a conjecture',
  'Doubt: uncertainty or lack of conviction',
  'Every: each and all',
  'Frame: a rigid structure that surrounds or encloses something',
  "Guest: a person who is invited to visit someone else's home",
  'Dozen: a group or set of twelve',
  'Exact: precisely or accurately representing the truth',
  'Frank: open, honest, and direct in speech or expression',
  'Guide: a person who leads or directs others',
  'Draft: a preliminary version of a written work',
  'Exist: to have actual being or reality',
  'Fraud: wrongful or criminal deception',
  'Happy: feeling or showing pleasure or contentment',
  'Drama: a genre of literature or performance that involves conflict and emotion',
  'Extra: more than is usual or necessary',
  'Fresh: newly made or obtained; not canned, frozen, or otherwise preserved',
  'Harry: to persistently harass or annoy',
  'Drawn: pulled or dragged',
  'Faith: complete trust or confidence in someone or something',
  'Front: the forward-facing part or side',
  'Heart: the central organ of the circulatory system',
  'Dream: a succession of images, ideas, emotions, and sensations',
  'False: not in accordance with truth or fact',
  'Fruit: the sweet or savory edible product of a plant',
  'Heavy: of great weight or intensity',
  'Dress: to put on clothes',
  'Fault: responsibility for an error or mistake',
  'Fully: completely or entirely',
  'Hence: as a consequence; for this reason',
  'Drill: a tool or machine used for making holes',
  'Fiber: a thread-like structure that forms part of a plant or animal',
  'Funny: causing laughter or amusement',
  'Night: the period of darkness between sunset and sunrise',
  'Drink: to consume a liquid through the mouth',
  'Field: an area of open land',
  'Giant: an imaginary or mythical being of human form but superhuman size',
  'Horse: a large, four-legged animal used for riding or pulling loads',
   "Drive: operate and control the direction and speed of a motor vehicle",
  'Fifth: constituting number five in a sequence',
  'Given: past participle of give; provided or supplied with',
  'Drove: past tense of drive; operated and controlled the direction and speed of a motor vehicle',
  'Fifty: the number equivalent to the product of five and ten',
  'Glass: a hard, brittle substance, typically transparent or translucent',
  'House: a building for human habitation',
  'Dying: ceasing to live or exist',
  'Fight: take part in a violent struggle',
  'Globe: the earth, especially when regarded as a planet',
  'Human: of, relating to, or characteristic of people',
  'Eager: strongly wanting to do or have something',
  'Final: coming at the end of a series',
  'Going: the act or process of leaving or departing',
  "Ideal: satisfying one's conception of what is perfect",
  'Early: happening or done before the usual or expected time',
  'First: coming before all others in time or order',
  'Grace: simple elegance or refinement of movement',
  'Image: a representation of the external form of a person or thing',
  'Earth: the planet on which we live',
  'Fixed: fastened securely in position',
  'Grade: a particular level of rank, quality, or achievement',
  'Index: an alphabetical listing of names, topics, etc.',
  'Eight: constituting number eight in a sequence',
  'Flash: a sudden brief burst of bright light',
  'Grand: magnificent or imposing in appearance',
  'Inner: situated inside or further in',
  'Elite: a select group that is superior in terms of ability or qualities',
  'Fleet: a group of ships sailing together',
  'Grant: agree to give or allow (something requested) to',
  'Input: data that is entered into a computer or other device',
  'Empty: containing nothing; not filled or occupied',
  'Floor: the lower surface of a room',
  'Grass: vegetation consisting of short plants',
  'Issue: an important topic or problem for debate or discussion',
         'Drive: operate and control the direction and speed of a motor vehicle',
  'Fifth: constituting number five in a sequence',
  'Given: past participle of give; provided or supplied with',
  'Drove: past tense of drive; operated and controlled the direction and speed of a motor vehicle',
  'Fifty: the number equivalent to the product of five and ten',
  'Glass: a hard, brittle substance, typically transparent or translucent',
  'House: a building for human habitation',
  'Dying: ceasing to live or exist',
  'Fight: take part in a violent struggle',
  'Globe: the earth, especially when regarded as a planet',
  'Human: of, relating to, or characteristic of people',
  'Eager: strongly wanting to do or have something',
  'Final: coming at the end of a series',
  'Going: the act or process of leaving or departing',
  "Ideal: satisfying one's conception of what is perfect",
  'Early: happening or done before the usual or expected time',
  'First: coming before all others in time or order',
  'Grace: simple elegance or refinement of movement',
  'Image: a representation of the external form of a person or thing',
  'Earth: the planet on which we live',
  'Fixed: fastened securely in position',
  'Grade: a particular level of rank, quality, or achievement',
  'Index: an alphabetical listing of names, topics, etc.',
  'Eight: constituting number eight in a sequence',
  'Flash: a sudden brief burst of bright light',
  'Grand: magnificent or imposing in appearance',
  'Inner: situated inside or further in',
  'Elite: a select group that is superior in terms of ability or qualities',
  'Fleet: a group of ships sailing together',
  'Grant: agree to give or allow (something requested) to',
  'Input: data that is entered into a computer or other device',
  'Empty: containing nothing; not filled or occupied',
  'Floor: the lower surface of a room',
  'Grass: vegetation consisting of short plants',
  'Issue: an important topic or problem for debate or discussion',
  'Enemy: a person who is actively opposed or hostile to someone or something',
  'Fluid: a substance that flows and takes the shape of its container',
  'Great: of an extent, amount, or intensity considerably above average',
  "Irony: the expression of one's meaning by using language that normally signifies the opposite",
  'Enjoy: take pleasure in something',
  'Focus: the center of interest or activity',
  'Green: of the color between blue and yellow',
  'Juice: a liquid drink, typically made from fruit',
  'Enter: come or go into a place',
  'Force: strength or energy as an attribute of physical action or movement',
  'Gross: total or entire, especially before any deductions',
  'Joint: a point at which parts of an artificial structure are joined',
  'Judge: a public officer appointed to decide cases in a court of law',
  'Metal: a solid material that is typically hard, shiny, malleable, and ductile',
  'Media: the main means of mass communication',
  'Newly: recently; not long ago',
  'Known: recognized or familiar',
      ]

      const sixLetters = [
         'Abroad: in or to a foreign country or countries',
  'Casual: relaxed or informal in style or nature',
  'Around: located or situated on every side',
  'Couple: two individuals considered as a pair',
  'Accept: to receive willingly or agree to',
  'Caught: past tense of catch, to capture or seize',
  'Arrive: to reach a destination or come to a place',
  'Course: a path or direction of movement',
  'Access: the ability or right to enter or use',
  'Center: the middle point or part',
  'Artist: a person who creates art',
  'Covers: provides protection or concealment',
  'Across: from one side to the other',
  'Centre: the central point or focus',
  'Aspect: a particular part or feature',
  'Create: to bring into existence or produce',
  'Acting: performing in a play or film',
  'Chance: an opportunity or possibility',
  'Assess: to evaluate or determine the value or quality',
  'Credit: recognition or acknowledgement for achievement',
  'Action: the process of doing something',
  'Change: to make or become different',
  'Assist: to help or support',
  'Crisis: a time of intense difficulty or danger',
        'Active: engaged in action or participation',
  'Charge: to demand or ask as a price or fee',
  'Assume: to take on or adopt as true or valid',
  'Custom: a traditional or habitual practice',
  'Actual: existing in fact or reality',
  'Choice: the act of selecting or making a decision',
  'Attack: to act aggressively or forcefully against',
  'Damage: harm or injury to something or someone',
  'Advice: a recommendation or suggestion',
  'Choose: to select or pick out from a set of options',
  'Attend: to be present at or go to regularly',
  'Danger: a state of being exposed to harm or risk',
  'Advise: to give counsel or guidance',
  'Chosen: selected or picked out',
  'August: the eighth month of the year',
  'Dealer: a person or business that sells goods',
  'Affect: to influence or produce a change in',
  'Church: a building for public Christian worship',
  'Author: a person who writes books or articles',
  'Debate: a formal discussion on a particular topic',
  'Afford: to have enough money or resources to do or buy something',
  'Circle: a round plane figure',
  'Avenue: a wide road or thoroughfare',
  'Decade: a period of ten years',
         'Afraid: feeling fear or apprehension',
  'Client: a person or organization that uses the services or advice of a professional',
  'Backed: supported or financed',
  'Decide: to make a choice or reach a conclusion',
  'Agency: a business or organization providing a particular service',
  'Closed: not open or accessible',
  'Barely: only just; scarcely',
  'Defeat: to win a victory over; overcome',
  'Agenda: a list or plan of things to be done or considered',
  'Closer: nearer in space or time',
  'Battle: a sustained fight between large organized armed forces',
  'Defend: to protect from harm or danger',
  'Almost: not quite; nearly',
  'Coffee: a hot drink made from roasted coffee beans',
  'Beauty: the quality of being pleasing to the senses or the mind',
  'Define: to state or describe the exact meaning of',
  'Always: at all times; on all occasions',
  'Column: a vertical pillar supporting a structure',
  'Became: past tense of "become"',
  'Degree: a unit of measurement of angles',
  'Amount: a quantity of something',
  'Combat: a fight or conflict between individuals or groups',
  'Become: to begin to be or develop into something',
  'Demand: an insistent and peremptory request',
         'Animal: a living organism that feeds on organic matter',
  'Coming: the act of arriving or approaching',
  'Before: during the period of time preceding a particular event',
  'Depend: to rely on or be influenced by someone or something',
  'Annual: occurring once every year',
  'Common: occurring or found frequently or widely',
  'Behalf: as a representative of; on behalf of',
  'Deputy: a person who is appointed to take the place of another',
  'Answer: a response to a question, problem, or request',
  'Comply: to act in accordance with a request, command, or rule',
  'Behind: at or to the far side of something',
  'Desert: a barren or desolate area, often sandy',
  'Anyone: any person or people; whoever',
  'Copper: a chemical element with symbol Cu',
  'Belief: an acceptance that something is true or exists',
  'Design: to plan or create according to a specific purpose or intention',
  'Anyway: in any case; regardless of other considerations',
  'Corner: the point at which two lines or edges meet',
  'Belong: to be the property of or connected with',
  'Desire: a strong feeling of wanting or wishing for something',
  'Appear: to become visible or evident',
  'County: a territorial division within a state or country',
  'Better: of higher quality or more desirable',
  'Detect: to discover or identify the presence or existence of something',
          'Beyond: at or to the further side of',
  'Budget: an estimate of income and expenditure for a set period of time',
  'During: throughout the course or duration of',
  'Device: a thing made or adapted for a particular purpose',
  'Bishop: a senior member of the Christian clergy',
  'Burden: a heavy load, typically carried or borne',
  'Easily: without difficulty or effort',
  'Differ: to be unlike or distinct in nature or quality',
  'Border: the line separating two countries or areas',
  'Bureau: an office or department for a specific purpose',
  'Eating: the act of consuming food',
  'Dinner: the main meal of the day, typically eaten in the evening',
  'Bottle: a container with a narrow neck, used for storing liquids',
  'Button: a small disk or knob sewn onto a garment',
  'Editor: a person who prepares written material for publication',
  'Direct: to control the operations of; manage or govern',
  'Bottom: the lowest point or part',
  'Camera: a device for taking photographs or recording videos',
  'Effect: a change that is a result or consequence of an action',
  'Doctor: a qualified practitioner of medicine',
  'Bought: past tense and past participle of "buy"',
  'Cancer: a disease caused by the uncontrolled division of abnormal cells',
  'Effort: the physical or mental energy exerted to accomplish a task',
  'Dollar: the basic monetary unit of the United States and several other countries',
       'Branch: a part of a tree that grows out from the trunk',
  'Cannot: can not; is unable to',
  'Eighth: constituting number eight in a sequence',
  'Domain: an area of territory owned or controlled by a ruler or government',
  'Breath: the air taken into or expelled from the lungs',
  'Carbon: a chemical element with symbol C and atomic number 6',
  'Either: one or the other of two people or things',
  'Double: consisting of two equal, identical, or similar parts',
  'Bridge: a structure built to span a physical obstacle',
  'Career: an occupation or profession, especially one requiring special training',
  'Eleven: the number equivalent to the sum of ten and one',
  'Driven: past participle of "drive"; compelled or determined by something',
  'Bright: giving out or reflecting a lot of light; shining',
  'Castle: a large building fortified against attack',
  'Emerge: move out of or away from something and come into view',
  'Driver: a person who drives a vehicle',
      ];
      

      const sevenLetters= [
         'Ability: the power or skill to do something',
  'Backing: support or assistance',
  'Cabinet: a cupboard with drawers or shelves for storing or displaying items',
  'Absence: the state of being away or not present',
  'Balance: an even distribution of weight enabling someone or something to remain upright and steady',
  'Caliber: the internal diameter or bore of a gun barrel',
  'Academy: a school or learned society',
  'Banking: the business conducted or services offered by a bank',
  'Calling: a strong urge toward a particular way of life or career',
  'Account: a record or statement of financial expenditure and receipts',
  'Barrier: a fence, railing, or other upright structure that prevents access or escape',
  'Capable: having the ability, fitness, or quality necessary to do or achieve a specified thing',
  'Accused: a person or group of people who are charged with or on trial for a crime',
  'Battery: a container consisting of one or more cells that produces an electric current',
  'Capital: the most important city or town of a country or region, usually its seat of government',
  'Achieve: successfully bring about or reach a desired objective, level, or result',
  "Bearing: a person's way of standing or moving",
  'Captain: the person in command of a ship, aircraft, or team',
  'Acquire: buy or obtain for oneself',
  'Beating: the action of striking repeatedly',
  'Caption: a title or brief explanation accompanying an illustration, cartoon, or poster',
  'Address: the particulars of the place where someone lives or an organization is situated',
  'Because: for the reason that; since',
  "Capture: take into one's possession or control by force",
  'Advance: move forward in a purposeful way',
  'Bedroom: a room for sleeping in',
  'Careful: making sure of avoiding potential danger, mishap, or harm',
  'Adverse: preventing success or development; harmful; unfavorable',
  'Believe: accept that (something) is true or exists',
  'Carrier: a person or company that undertakes the professional conveyance of goods or people',
  'Advised: having been given information, typically by someone in a position of authority or expertise',
  'Beneath: extending or directly underneath something',
        'Caution: care taken to avoid danger or mistakes',
  'Adviser: a person who gives advice in a particular field',
  'Benefit: an advantage or profit gained from something',
  'Ceiling: the upper interior surface of a room',
  'Against: in opposition to',
  'Besides: in addition to; apart from',
  'Central: at the center; of central importance',
  'Airline: a company that provides regular flights for passengers',
  'Between: at, into, or across the space separating two objects',
  'Centric: having a specified center or focus',
  'Airport: a place where aircraft regularly take off and land',
  'Billion: a thousand million',
  'Century: a period of one hundred years',
  'Alcohol: a colorless volatile flammable liquid',
  'Binding: the action of fastening or being fastened with a tie, rope, or other cord',
  'Certain: known for sure; established beyond doubt',
  'Alleged: said, without proof, to have taken place or to have a specified illegal or undesirable quality',
  'Brother: a man or boy in relation to other sons and daughters of his parents',
  'Chamber: a large room used for formal or public events',
         'Already: before or by now or the time in question',
  'Brought: past tense and past participle of "bring"',
  'Channel: a means of communication or expression',
  'Analyst: a person who conducts analysis or examination',
  'Burning: the act or process of combustion',
  'Chapter: a main division of a book or other written work',
  'Ancient: belonging to the very distant past',
  'Dealing: the activity of buying and selling goods and services',
  'Charity: the voluntary giving of help',
  'Another: one more; a further',
  'Decided: having made a firm decision',
  'Charlie: a given name; also used in various contexts',
  'Anxiety: a feeling of unease',
  'Decline: a gradual and continuous loss of strength',
  'Charter: a written grant of rights',
  'Anxious: experiencing worry or unease',
  'Default: failure to fulfill an obligation',
  'Checked: having a pattern of squares or rectangles',
  'Anybody: any person at all',
  'Defence: the action of defending from or resisting attack',
  'Chicken: a domestic fowl kept for its eggs or meat',
  'Applied: put into practical use',
  'Deficit: the amount by which something is too small',
  'Chronic: persisting for a long time or constantly recurring',
       'Arrange: put in a particular order or sequence',
  'Deliver: bring or transport goods to a destination',
  'Circuit: a complete and closed path of an electric current',
  'Adviser: a person who gives advice or recommendations',
  'Benefit: an advantage or profit gained from something',
  'Ceiling: the upper interior surface of a room',
  'Against: in opposition to; in conflict with',
  'Besides: in addition to; apart from',
  'Central: at, in, or forming the center',
  'Airline: a company that provides air transport services',
  'Between: at, into, or across the space separating two objects',
  'Centric: having a center or focus',
  'Airport: a place where aircraft can take off and land',
  'Billion: a thousand million; 1,000,000,000',
  'Century: a period of 100 years',
  'Alcohol: a flammable liquid used as a solvent or in drinks',
  'Binding: fastening or securing with a string, cord, or similar',
  'Certain: known for sure; established beyond doubt',
  'Alleged: claimed or asserted without proof',
  'Brother: a male sibling',
  'Chamber: a large room used for formal or public events',
        'Already: previously; before now',
  'Brought: past tense of "bring"; to carry or accompany to a place',
  'Channel: a passage for conveying fluids or transmitting information',
  'Analyst: a person who examines and interprets data or information',
  'Burning: on fire; undergoing combustion',
  'Chapter: a main division of a book or a distinct period in history',
  'Ancient: belonging to the very distant past; old',
  'Dealing: the act of engaging in business or negotiations',
  'Charity: the voluntary giving of help to those in need',
  'Another: one more; an additional person or thing',
  'Decided: having made a firm decision; determined',
  'Charlie: a given name; a friendly form of address',
  'Anxiety: a feeling of unease or worry',
  'Decline: to become smaller, weaker, or less',
  'Charter: a written grant of authority or rights',
  'Anxious: feeling worried or uneasy',
  'Default: failure to fulfill an obligation or repay a debt',
  'Checked: examined or verified for accuracy or correctness',
  'Anybody: any person at all; someone',
  'Defence: the action of defending from or resisting an attack',
  'Chicken: a domestic fowl raised for its meat or eggs',
  'Applied: put to practical use; used in a specific context',
  'Deficit: the amount by which something is less than expected or required',
  'Chronic: persisting for a long time; long-lasting',
        'Arrange: to put things in a particular order or position',
  'Deliver: to bring or transport something to a specific destination',
  'Circuit: a circular route or path; an electrical pathway',
  'Elderly: of old age; advanced in years',
  'Dispute: a disagreement or argument',
  'Compact: closely and neatly packed together; small in size',
  'Element: a component or fundamental part of something',
  'Distant: far away in space or time; remote',
  'Company: a business organization; a group of people',
  'Engaged: busy or occupied with a task or activity',
  'Diverse: varied or different in nature or form',
  'Compare: to examine similarities and differences between things',
  'Enhance: to improve or increase the quality or value of something',
  'Divided: separated or split into parts',
  'Compete: to strive or contend against others',
  'Essence: the fundamental nature or quality of something',
  'Drawing: the act of creating a picture or representation',
  'Complex: consisting of many interconnected parts; intricate',
  'Evening: the period of time between afternoon and night',
  'Driving: operating or controlling a vehicle',
  'Concept: an abstract idea or general notion',
       'Evident: easily seen or understood; apparent',
  'Dynamic: characterized by constant change, activity, or progress',
  'Concern: a feeling of worry, interest, or care',
  'Exactly: in a precise or accurate manner',
  'Factory: a building or establishment where goods are manufactured',
  'Concert: a musical performance',
  'Examine: to inspect, scrutinize, or investigate',
  'Faculty: the teaching staff of a university or college',
  'Conduct: the manner in which a person behaves',
  'Example: a representative instance or illustration',
  'Failing: a weakness or shortcoming',
  'Confirm: to establish the truth or validity of something',
  'Excited: feeling or showing enthusiasm or exhilaration',
  'Failure: the lack of success or accomplishment',
  'Connect: to join or link together',
  'Exclude: to prevent from entering or being included',
  'Fashion: a popular trend or style',
  'Consent: permission or agreement',
  'Exhibit: to display or show publicly',
  'Feature: a distinctive attribute or characteristic',
  'Consist: to be made up or composed of',
  'Expense: the cost or expenditure of something',
  'Federal: relating to a central government',
  'Contact: the act of communication or interaction',
          'Explain: to make clear or understandable',
  'Feeling: an emotional state or reaction',
  'Contain: to hold or include within its limits',
  'Explore: to travel through or investigate',
  'Fiction: imaginative or invented storytelling',
  'Content: the substance or subject matter',
  'Express: to convey or communicate',
  'Fifteen: the number after fourteen',
  'Contest: a competition or challenge',
  'Extreme: reaching a high degree or intensity',
  'Filling: material used to fill a space or cavity',
  'Context: the circumstances or setting',
  'Gallery: a room or building for displaying artwork',
  'Finance: the management of money or funds',
  'Control: to have power or influence over',
  'Gateway: an entrance or access point',
  'Finding: a discovery or conclusion',
  'Convert: to change from one form to another',
  'General: relating to all or most members',
  'Fishing: the act of catching fish',
  'Correct: free from error or mistake',
  'Genetic: relating to genes or heredity',
  'Fitness: the state of being physically healthy',
  'Council: a group of people who provide advice or make decisions',
  'Genuine: real or authentic',
  'Foreign: of or from another country',
  'Counsel: advice or guidance',
        'Gigabit: a unit of information equal to one billion bits',
  'Forever: for all future time; eternally',
  'Counter: a device that counts or keeps track of something',
  'Greater: larger in size, amount, or degree',
  'Formula: a set of instructions or principles',
  'Country: a nation or state',
  'Hanging: suspended or attached from above',
  'Fortune: a large amount of wealth or prosperity',
  'Crucial: extremely important or decisive',
  'Heading: a title or caption at the top of a page or section',
  'Forward: in the direction that one is facing or moving',
  'Crystal: a clear, transparent mineral or substance',
  'Healthy: in good physical or mental condition',
  'Founder: a person who establishes or creates something',
  'Culture: the customs, arts, and achievements of a particular group',
  'Hearing: the ability to perceive sounds',
  'Freedom: the state of being free or unrestricted',
  'Current: belonging to the present time',
  'Heavily: to a great extent or degree',
  'Further: at or to a greater distance or more advanced point',
  'Cutting: the action of using a sharp tool to divide or separate',
  'Helpful: providing assistance or support',
  'Illegal: not allowed by law',
  'Jointly: in conjunction or cooperation with others',
         'Helping: the action of assisting or giving aid',
  'Illness: a state of poor health or disease',
  'Journal: a daily record of events, experiences, or observations',
  'Herself: the reflexive form of "she"',
  'Imagine: to form a mental image or concept of something',
  'Journey: a long trip or travel from one place to another',
  'Highway: a main road, typically connecting major cities or towns',
  'Imaging: the process of creating an image or visual representation',
  'Justice: the quality of being fair and morally right',
  'Extreme: reaching a high or very great degree',
  'Filling: material used to fill a cavity or space',
  'Context: the circumstances or setting in which something occurs',
  'Gallery: a room or building for the display of art or exhibitions',
  'Finance: the management of money, banking, investments, etc.',
  'Control: the power to influence or direct the behavior of others',
  'Gateway: an entrance or access point to a place or network',
  'Finding: the act of discovering or determining something',
  'Convert: to change something into a different form or use',
  'General: affecting or involving all or most people or things',
  'Fishing: the activity of catching fish',
  'Correct: free from error or mistake',
  'Genetic: relating to genes or heredity',
  'Fitness: the condition of being physically fit and healthy',
  'Council: a group of people chosen to make decisions or provide advice',
  'Genuine: truly what it is said to be; authentic',
  "Foreign: of, from, or characteristic of a country or language other than one's own",
  'Counsel: advice, especially given formally',
         'Gigabit: a unit of information equal to 1,073,741,824 bits',
  'Forever: for all future time; eternally',
  'Counter: a device used to count or keep track of something',
  'Greater: of a larger size or more advanced nature',
  'Formula: a set of instructions or a recipe for achieving something',
  'Country: a nation or territory considered as an organized political community',
  'Hanging: suspending or attaching something from above',
  'Fortune: a large amount of money or wealth',
  'Crucial: of great importance; decisive',
  'Heading: a title or caption at the top of a page or section',
  'Forward: in a direction ahead or toward the front',
  'Crystal: a clear, transparent mineral or glass with a regular geometric shape',
  'Healthy: in a good physical or mental condition',
  'Founder: a person who establishes an organization or business',
  'Culture: the customs, arts, social institutions, and achievements of a particular nation, people, or group',
  'Hearing: the faculty or sense by which sound is perceived',
  'Freedom: the power or right to act, speak, or think as one wants',
  'Current: belonging to the present time; happening or being used or done at the moment',
  'Heavily: to a great degree; in a heavy manner',
  'Further: at, to, or by a greater distance or more advanced point',
  'Cutting: the action or process of cutting something',
  'Helpful: giving or providing help; useful',
  'Illegal: forbidden by law or statute',
  'Jointly: in cooperation or collaboration with others',
  'Helping: the action of assisting or giving aid',
  'Illness: a state of poor health or disease',
  'Journal: a daily record of events, experiences, or observations',
  'Herself: the reflexive form of "she"',
  'Imagine: to form a mental image or concept of something',
  'Journey: a long trip or travel from one place to another',
          'Highway: a main road, especially one connecting major towns or cities',
  'Imaging: the process or technique of forming an image of an object or person',
  'Justice: the quality of being just, fair, or morally right',
  'Himself: the reflexive form of "him"',
  'Improve: to make or become better; enhance',
  'Justify: to show or prove to be right or reasonable',
  'History: the study of past events, particularly in human affairs',
  'Include: to comprise or contain as part of a whole',
  'Keeping: the action of retaining or holding something',
  'Holding: the act of grasping or gripping something',
  'Initial: occurring at the beginning; first',
  'Killing: the act of causing the death of a person or animal',
  'Holiday: a day of festivity or recreation when no work is done',
  'Inquiry: the act of asking for information; an investigation',
  'Kingdom: a country, state, or territory ruled by a king or queen',
  'Housing: the provision of lodging or accommodation',
  'Insight: the capacity to gain an accurate and deep understanding of someone or something',
  'Kitchen: a room or area where food is prepared and cooked',
  'However: nevertheless; nonetheless',
  'Install: to set up or place something in position for use',
  'Knowing: having knowledge or awareness; conscious',
  'Hundred: the number equivalent to the product of ten and ten; 100',
  'Instant: happening or coming immediately; without delay',
  'Machine: a device with moving parts designed to perform a particular task',
          'Husband: a married man considered in relation to his spouse',
  'Instead: as an alternative or substitute',
  'Manager: a person responsible for controlling or administering an organization or group of staff',
  'Landing: the act of coming down or bringing something down to the ground',
  'Intense: of extreme force, degree, or strength',
  'Married: having a spouse; joined in matrimony',
  'Largely: mostly; mainly',
  'Interim: an intervening time; temporary',
  'Massive: large and heavy or solid; imposing',
  'Lasting: continuing or enduring for a long time',
  'Involve: to include or contain as part of a whole',
  'Maximum: the greatest or highest possible amount or degree',
  'Leading: having the highest position or importance',
  'Natural: existing in or caused by nature; not made or caused by humankind',
  'Meaning: the idea or concept conveyed by a word, phrase, or action',
  'Learned: having acquired knowledge or skill through study or experience',
  'Neither: not one nor the other of two people or things',
  'Measure: a standard unit used to express the size, quantity, or degree of something',
  'Leisure: free time; time when one is not working or occupied',
  'Nervous: easily agitated or alarmed; anxious',
  'Medical: relating to the practice of medicine or the treatment of illness or injury',
  'Liberal: open to new behavior or opinions; tolerant and free-thinking',
  'Network: a group or system of interconnected people or things',
  'Meeting: an assembly of people for a particular purpose, especially for formal discussion',
        'Liberty: the state of being free within society from oppressive restrictions',
  'Neutral: not favoring any side or position; unbiased',
  'Mention: to refer to or briefly speak about',
  'Library: a building or room containing collections of books, periodicals, and sometimes films and recorded music',
  'Notable: deserving attention or notice; remarkable',
  'Message: a verbal, written, or recorded communication sent from one person or group to another',
  'License: an official or legal permission to do or own a specified thing',
  'Nothing: not anything; no single thing',
  'Million: the number equivalent to the product of a thousand and a thousand',
  'Limited: restricted in size, amount, or extent; not great or excessive',
  'Nowhere: not in or to any place; not anywhere',
  'Mineral: a solid, naturally occurring inorganic substance with a definite chemical composition',
  'Listing: a record of names or items arranged for quick reference or enumeration',
  'Nuclear: relating to the nucleus of an atom or the energy produced by nuclear reactions',
  'Minimal: of a minimum amount, quantity, or degree; negligible',
  'Logical: characterized by clear, sound reasoning; rational',
  'Nursing: the profession or practice of providing care for the sick or infirm',
  'Minimum: the least or smallest amount or quantity possible or attainable',
  'Loyalty: a strong feeling of support or allegiance',
  'Pacific: of, on, or near the coast of the Pacific Ocean',
  'Missing: not able to be found or located; lost',
  'Extreme: reaching a high or the highest degree; very great',
  'Filling: material used to fill a cavity or space',
  'Context: the circumstances or setting in which an event or statement occurs',
  'Gallery: a room or building for the display or sale of works of art',
  'Finance: the management of large amounts of money, especially by governments or large companies',
  "Control: the power to influence or direct people's behavior or the course of event",
         'Gateway: an entrance or means of access to a place',
  'Finding: the act of discovering or determining something previously unknown or hidden',
  'Convert: to change or make something change from one form, purpose, or system to another',
  'General: affecting or concerning all or most people, places, or things',
  'Fishing: the activity of catching fish, either for food or as a sport',
  'Correct: free from error; true, accurate, or right',
  'Genetic: relating to genes or heredity',
  'Fitness: the condition of being physically fit and healthy',
  'Council: a group of people elected or chosen to make decisions or give advice',
  'Genuine: truly what something is said to be; authentic',
  "Foreign: of, from, in, or characteristic of a country or language other than one's own",
  'Counsel: advice, especially given formally',
  'Gigabit: a unit of data equal to 1,073,741,824 bits',
  'Forever: for all future time; for always',
  'Counter: a long flat-topped fitment across which business is conducted',
  'Greater: of an extent, amount, or intensity considerably above the normal or average',
  'Formula: a mathematical relationship or rule expressed in symbols',
  'Country: a nation with its own government, occupying a particular territory',
  'Hanging: suspended in the air or attached to something above',
  'Fortune: a large amount of money or assets',
  'Crucial: of great importance; decisive or critical',
  'Heading: a title or caption at the head of a page or section of a book',
  'Forward: toward or at a place or position ahead',
  'Crystal: a piece of a homogeneous solid substance with a regular geometric shape',
         'Healthy: in a good physical or mental condition; in good health',
  'Founder: a person who establishes an institution, company, or organization',
  'Culture: the arts, customs, beliefs, and other manifestations of human intellectual achievement',
  'Hearing: the faculty or sense by which sound is perceived',
  'Freedom: the power or right to act, speak, or think as one wants',
  'Current: belonging to the present time; happening or being used or done now',
  'Heavily: to a great extent; with great weight, force, or intensity',
  'Further: at, to, or by a greater distance or more advanced point',
  'Cutting: the action of using a sharp tool or object to divide something into parts',
  'Helpful: giving or ready to give help; useful',
  'Illegal: forbidden by law or statute',
  'Jointly: together; in cooperation or partnership with others',
  'Helping: giving assistance; being of service',
  'Illness: a disease or period of sickness affecting the body or mind',
  'Journal: a daily record of news and events of a personal nature',
  'Herself: used as the object of a verb or preposition to refer to a female person',
  'Imagine: to form a mental image or concept of something not present to the senses',
  'Journey: an act of traveling from one place to another',
  'Highway: a main road, especially one connecting major towns or cities',
  'Imaging: the formation of an image, likeness, or representation of someone or something',
  'Justice: just behavior or treatment; fairness',
  'Himself: used to refer to a male person as the object of a verb or preposition',
  'Improve: to make or become better',
  'Justify: to show or prove to be right or reasonable',
         'History: the study of past events, particularly in human affairs',
  'Include: to comprise or contain as part of a whole',
  'Keeping: the action of retaining or holding something',
  'Holding: the action of gripping or grasping something',
  'Initial: existing or occurring at the beginning',
  "Killing: the act of causing someone's death",
  'Holiday: a day of festivity or recreation when no work is done',
  'Inquiry: the act of seeking information or knowledge',
  'Kingdom: a country, state, or territory ruled by a king or queen',
  'Housing: buildings or structures that serve as living spaces',
  'Insight: the capacity to gain an accurate and deep understanding',
  'Kitchen: a room or area where food is prepared and cooked',
  'However: nevertheless; nonetheless',
  'Install: to set up or establish something, typically equipment or software',
  'Knowing: having knowledge or awareness',
  'Hundred: the number equivalent to the product of ten and ten',
  'Instant: happening or coming immediately',
  'Machine: a device that uses power to perform a task',
  'Husband: a married man considered in relation to his spouse',
  'Instead: in place of; as an alternative or substitute',
  'Manager: a person responsible for controlling or administering an organization',
  'Landing: the act of coming to or bringing something to rest on a surface',
  'Intense: of extreme force, degree, or strength',
  'Married: joined in marriage; having a spouse',
        'Largely: mainly; mostly',
  'Interim: temporary; provisional',
  'Massive: large and heavy; bulky',
  'Lasting: enduring; continuing for a long time',
  'Involve: to include or incorporate as a necessary part',
  'Maximum: the greatest possible amount, extent, or degree',
  'Leading: occupying the foremost position in a list or ranking',
  'Natural: existing in or caused by nature; not artificial',
  'Meaning: the purpose or significance of something',
  'Learned: having acquired knowledge or skill through study or experience',
  'Neither: not one nor the other of two specified alternatives',
  'Measure: a standard unit or quantity used for comparison',
  'Leisure: free time; time when one is not working or occupied',
  'Nervous: easily agitated or alarmed; anxious',
  'Medical: relating to the field of medicine or healthcare',
  'Liberal: open to new behavior or opinions; tolerant',
  'Network: a group or system of interconnected people or things',
  'Meeting: an assembly or gathering of people, typically for a specific purpose',
  'Liberty: the state of being free from oppressive restrictions',
  'Neutral: not supporting or favoring any particular side or party',
  'Mention: to refer to something briefly or casually',
  'Library: a building or room containing collections of books',
  'Notable: worthy of attention or notice; remarkable',
  'Message: a verbal, written, or recorded communication sent to someone',
         'License: a legal document giving official permission to do something',
  'Nothing: not anything; no single thing',
  'Million: the number equivalent to one thousand thousand',
  'Limited: restricted or confined within certain boundaries',
  'Nowhere: in or to no place; not anywhere',
  'Mineral: a solid, naturally occurring substance with a specific chemical composition',
  'Listing: a printed or written list of items or information',
  'Nuclear: relating to the nucleus of an atom or nuclear energy',
  'Minimal: of a minimum amount, quantity, or degree',
  'Logical: based on reasoning or rationality',
  'Nursing: the profession or practice of caring for the sick or injured',
  'Minimum: the least or smallest amount or quantity',
  'Loyalty: the quality of being faithful or devoted to someone or something',
  'Pacific: peaceful; calm; not aggressive',
  'Missing: not present or accounted for; lost',
  'Obvious: easily perceived or understood; clear',
  'Package: a wrapped or boxed object or group of objects',
  'Mission: an important assignment or task',
  'Offense: an illegal act; a violation',
  'Painted: covered with paint; colored',
  'Mistake: an error or fault resulting from a misunderstanding or misjudgment',
  'Officer: a person in a position of authority in an organization or government',
  'Parking: the act of leaving a vehicle in a certain place for a period of time',
  'Mixture: a combination of different elements or substances',
          'Ongoing: currently happening or in progress',
  'Partial: incomplete; not whole',
  'Monitor: to observe, watch, or keep track of something',
  'Opening: an aperture or gap that allows access or passage',
  'Partner: a person or entity joined with another in an activity or endeavor',
  'Monthly: occurring once a month or every month',
  'Operate: to control or work with a machine, system, or organization',
  'Passage: a way or path for moving through or along',
  'Morning: the early part of the day; from dawn until noon',
  'Opinion: a personal belief, judgment, or viewpoint',
  'Passing: temporary; not permanent',
  'Musical: related to or associated with music',
  'Optical: relating to or involving sight, vision, or light',
  'Passion: a strong and intense emotion or enthusiasm',
  'Mystery: something that is difficult or impossible to understand or explain',
  'Organic: relating to or derived from living matter',
  'Passive: inactive; not active or participating',
  'Portion: a part or share of a whole',
  'Outcome: the result or consequence of an action or event',
  'Patient: a person under medical care or treatment',
  'Poverty: the state of being extremely poor',
  'Outdoor: relating to or designed for use outside',
  'Pattern: a repeated decorative design or arrangement',
  'Precise: exact; accurate; clearly defined',
        'Outlook: a person\'s point of view or expectation for the future',
  'Payable: capable of being paid',
  'Predict: to foretell or forecast future events or outcomes',
  'Outside: located or occurring on the outer side or surface',
  'Payment: the act or process of paying for something',
  'Premier: first in importance, rank, or position',
  'Overall: including everything or everyone; general',
  'Penalty: a punishment or consequence for breaking a rule or law',
  'Premium: an additional amount paid for a better quality or service',
  'Program: a planned series of actions or events',
  'Pending: awaiting a decision or resolution',
  'Prepare: to make ready or get ready for something',
  'Project: a planned undertaking or task',
  'Pension: a regular payment made to a person who has retired',
  'Present: existing or occurring now; current',
  'Promise: a declaration or assurance that one will do something',
  'Percent: a proportion or fraction of 100',
  'Prevent: to stop something from happening or from doing something',
  'Promote: to help or encourage the growth or development of something',
  'Perfect: having all the required or desirable qualities',
  'Primary: first in importance, order, or sequence',
  'Protect: to keep safe from harm, damage, or loss',
  'Perform: to carry out or execute a task or action',
  'Printer: a machine that produces printed copies of text or images',
         'Extreme: very great in degree or extent',
  'Filling: the material used to fill something',
  'Context: the circumstances or setting in which something occurs',
  'Gallery: a room or building for the display or sale of works of art',
  'Finance: the management of money and other assets',
  'Control: the power to influence or direct behavior or course of events',
  'Gateway: an entrance or access point',
  'Finding: a conclusion or opinion reached after investigation or research',
  'Convert: to change or make something into a different form or use',
  'General: relating to or affecting all or most people or things',
  'Fishing: the activity of catching fish',
  'Correct: free from error or mistakes',
  'Genetic: relating to genes or heredity',
  'Fitness: the condition of being physically fit and healthy',
  'Council: a group of people elected or appointed to make decisions',
  'Genuine: truly what it is said to be; authentic',
  "Foreign: of, from, or characteristic of a country or language other than one's own",
  'Counsel: advice or guidance, especially as given by a professional',
  'Gigabit: a unit of data equal to one billion bits',
  'Forever: for all future time; indefinitely',
  'Counter: a long flat-topped fitment across which business is conducted',
  'Greater: of an extent, amount, or intensity above average',
  'Formula: a mathematical relationship or rule expressed in symbols',
  'Country: a nation with its own government, occupying a particular territory',
          'Hanging: suspending or attaching something from above',
  'Fortune: a large amount of wealth or financial success',
  'Crucial: extremely important or necessary',
  'Heading: a title or caption at the top of a page or section',
  'Forward: in the direction that one is facing or moving',
  'Crystal: a clear, transparent mineral or glass',
  'Healthy: in good physical or mental condition',
  'Founder: a person who establishes an organization or business',
  'Culture: the beliefs, customs, arts, etc., of a particular society or group',
  'Hearing: the faculty or sense of perceiving sound',
  'Freedom: the power or right to act, speak, or think as one wants',
  'Current: belonging to the present time; happening or being used or done now',
  'Heavily: to a great extent; with a lot of weight or force',
  'Further: to a greater extent or degree; additional',
  'Cutting: the action or process of dividing something with a sharp tool',
  'Helpful: giving or ready to give help',
  'Illegal: contrary to or forbidden by law',
  'Jointly: in conjunction with others; together',
  'Helping: giving assistance; being of aid',
  'Illness: a disease or period of sickness affecting the body or mind',
  'Journal: a daily record of events or experiences; a diary',
  'Herself: used to refer to a female object of a verb or preposition',
  'Imagine: to form a mental image or concept of something not present',
  'Journey: an act of traveling from one place to another',
        'Highway: a main road, typically with two or more lanes',
  'Imaging: the production of images, especially by medical scanning',
  'Justice: the quality of being fair and just',
  'Himself: used to refer to a male object of a verb or preposition',
  'Improve: to make or become better; enhance',
  'Justify: to show or prove to be right or reasonable',
  'History: the study of past events, particularly in human affairs',
  'Include: to comprise or contain as part of a whole',
  'Keeping: the action of retaining or holding something',
  'Holding: the act of grasping or gripping something',
  'Initial: existing or occurring at the beginning',
  "Killing: the act of causing someone's death",
  'Holiday: a day of festivity or recreation when no work is done',
  'Inquiry: an act of asking for information',
  'Kingdom: a country, state, or territory ruled by a king or queen',
  'Housing: buildings or structures that people live in',
  'Insight: the capacity to gain an accurate and deep understanding',
  'Kitchen: a room or area where food is prepared and cooked',
  'However: nevertheless; nonetheless',
  'Install: to place or fix in position for use',
  'Knowing: having knowledge, information, or awareness',
  'Hundred: the number equivalent to the product of ten and ten',
  'Instant: happening or coming immediately',
  'Machine: an apparatus using mechanical power and having several parts',
         'Husband: a married man considered in relation to his spouse',
  'Instead: as an alternative or substitute',
  'Manager: a person responsible for controlling or administering an organization or group of staff',
  'Landing: the action or process of coming safely to the ground or another surface after a flight or jump',
  'Intense: of extreme force, degree, or strength',
  'Married: having a spouse; united in marriage',
  'Largely: mainly; for the most part',
  'Interim: the intervening time; meantime',
  'Massive: large and heavy or solid',
  'Lasting: enduring or able to endure over a long period of time',
  'Involve: to include or contain as a necessary part',
  'Maximum: the greatest possible amount or degree',
  'Leading: having the highest position or status',
  'Natural: existing in or caused by nature; not made or caused by humankind',
  'Meaning: the idea or concept conveyed by a word, phrase, or action',
  'Learned: having acquired knowledge or skill through study, experience, or being taught',
  'Neither: not one nor the other of two people or things',
  'Measure: a standard unit or quantity used for comparison or to express a quantity',
  'Leisure: free time; time when one is not working or occupied',
  'Nervous: easily agitated or alarmed; tending to be anxious',
  'Medical: relating to the science or practice of medicine',
  'Liberal: open to new behavior or opinions; favorable to or respectful of individual rights and freedoms',
  'Network: a group or system of interconnected people or things',
  'Meeting: an assembly of people for a particular purpose, especially for formal discussion',
         'Liberty: the state of being free within society from oppressive restrictions',
  'Neutral: not supporting or helping either side in a conflict, disagreement, or competition',
  'Mention: to refer to or speak about briefly or casually',
  'Library: a building or room containing collections of books and other materials for reading, study, or reference',
  'Notable: worthy of attention or notice; remarkable',
  'Message: a verbal, written, or recorded communication sent to or left for a recipient',
  'License: a permit from an authority to own or use something, do a particular thing, or carry on a trade',
  'Nothing: not anything; no single thing',
  'Million: the number equivalent to the product of a thousand and a thousand; 1,000,000',
  'Limited: restricted in size, amount, or extent; not great or excessive',
  'Nowhere: in or to no place; not anywhere',
  'Mineral: a solid, naturally occurring inorganic substance',
  'Listing: an entry in a list, directory, or catalog',
  'Nuclear: relating to the nucleus of an atom or the energy produced by nuclear reactions',
  'Minimal: of a minimum amount, quantity, or degree; very small or slight',
  'Logical: based on reason or sound judgment; reasonable',
  'Nursing: the profession or practice of providing care for the sick and infirm',
  'Minimum: the least or smallest amount or quantity possible or attainable',
  'Loyalty: a strong feeling of support or allegiance',
  'Pacific: peaceful in character or intent',
  'Missing: not able to be found or present; absent or lost',
  'Obvious: easily perceived or understood; clear, self-evident, or apparent',
  'Package: an object or group of objects wrapped in paper or packed in a box',
  'Mission: an important assignment or task that is given to a person or group',
         'Offense: an illegal act; a violation of the law or rules',
  'Painted: covered with paint; having been applied with paint',
  'Mistake: an error or blunder; a misunderstanding or misconception',
  'Officer: a person in a position of authority in a company, organization, or government',
  'Parking: the act of leaving a vehicle in a designated area',
  'Mixture: a combination or blend of different substances, elements, or things',
  'Ongoing: currently happening or in progress; continuing',
  'Partial: incomplete or limited; not total or whole',
  'Monitor: to observe, check, or keep track of something over time',
  'Opening: a gap, hole, or entrance that allows access or passage',
  'Partner: a person or entity who shares in an activity or business venture',
  'Monthly: occurring, done, or published once a month',
  'Operate: to control, manage, or work with a machine, system, or process',
  'Passage: a way or means of passing from one place to another',
  'Morning: the early part of the day, typically from sunrise to noon',
  'Opinion: a belief or judgment about something, formed without necessarily having complete knowledge or evidence',
  'Passing: moving past or going by; happening or occurring',
  'Musical: related to or characteristic of music; melodious or harmonious',
  'Optical: relating to or using light; visual',
  'Passion: a strong and intense emotion, desire, or enthusiasm',
  'Mystery: something that is difficult or impossible to understand, explain, or solve',
  'Organic: relating to or derived from living matter',
  'Passive: accepting or allowing what happens or what others do, without active response or resistance',
  'Portion: a part or share of a whole; a section or segment',
          'Outcome: the result or consequence of a particular action, event, or situation',
  'Patient: able to accept or tolerate delays, problems, or suffering without becoming annoyed or anxious',
  'Poverty: the state of being extremely poor; the condition of having insufficient resources or means of support',
  'Outdoor: relating to, occurring in, or suitable for the outdoors or open air',
  'Pattern: a repeated decorative design; a model, example, or guide for imitation or replication',
  'Precise: exact, accurate, or careful in details',
  'Outlook: a person\'s point of view or general attitude towards life or a particular situation',
  'Payable: able to be paid; relating to an amount of money that is owed',
  'Predict: to say or estimate that something will happen in the future',
  'Outside: located or situated on the exterior or outer side',
  'Payment: the act or process of paying someone or something; the transfer of money',
  'Premier: first in importance, order, or position; leading or most important',
  'Overall: taking everything into account; considering everything',
  'Penalty: a punishment imposed for breaking a law, rule, or contract',
  'Premium: a sum added to an ordinary price or charge; an additional cost or fee',
  'Program: a planned series of future events, performances, or activities',
  'Pending: awaiting a decision, settlement, or completion; not yet resolved or dealt with',
  'Prepare: to make ready or fit for a particular purpose or use; to get ready',
  'Project: a planned undertaking; a temporary endeavor with a specific goal or objective',
  'Pension: a regular payment made during a person\'s retirement from an investment fund to which that person or their employer has contributed during their working life',
  'Present: existing or occurring in a particular place, situation, or time',
  'Promise: a declaration or assurance that one will do a particular thing or that a particular thing will happen',
  'Percent: a proportion or ratio per hundred',
  'Prevent: to stop something from happening or someone from doing something',
         'Promote: to advance or raise to a higher position, rank, or status',
  'Perfect: having all the required or desirable elements, qualities, or characteristics',
  'Primary: of chief importance; principal or main',
  'Protect: to keep safe from harm, injury, or damage',
  'Perform: to carry out, accomplish, or fulfill an action, task, or function',
  'Printer: a machine that prints text or illustrations onto paper',
  'Protein: a large biomolecule composed of one or more chains of amino acids',
  'Perhaps: used to express uncertainty or possibility',
  'Privacy: the state or condition of being free from public attention or intrusion into one\'s private life',
  'Protest: a formal declaration or expression of objection, disapproval, or dissent',
  'Phoenix: a mythical bird that is cyclically reborn or regenerated from its ashes',
  'Private: belonging to or for the use of one particular person or group',
  'Provide: to make available or supply something for use or consideration',
  'Picking: the act of selecting or choosing something',
  'Problem: a matter or situation regarded as unwelcome or harmful that needs to be dealt with or solved',
  'Publish: to make a document or content available to the public, typically in printed or electronic form',
  'Picture: a visual representation or image produced by drawing, painting, or photography',
  'Proceed: to continue with an action or course of action',
  'Purpose: the reason for which something is done or created; the intention or objective',
  'Pioneer: a person who is among the first to explore or settle a new area or develop a new method, technique, or idea',
  'Process: a series of actions or steps taken to achieve a particular end',
  'Pushing: applying force to move something forward or away from oneself',
  'Plastic: a synthetic material made from a wide range of organic polymers',
  'Produce: to bring forth or yield a product, result, or outcome',
        'Qualify: to meet the necessary requirements or conditions',
  'Pointed: having a sharp or tapering end or tip',
  'Product: an item that is manufactured or produced for sale',
  'Quality: the standard or level of something as measured against other things of a similar kind',
  'Popular: liked, admired, or enjoyed by many people or by a particular person or group',
  'Profile: an outline or representation of something, typically a person\'s face, as seen from one side',
  'Quarter: each of four equal or corresponding parts into which something is or can be divided',
  'Section: a distinct part or component of something',
  'Success: the accomplishment of an aim or purpose',
  'Radical: relating to or affecting the fundamental nature of something; far-reaching or thorough',
  'Segment: each of the parts into which something is or may be divided',
  'Suggest: to put forward for consideration or action',
  'Railway: a track or set of tracks made of steel rails along which trains run',
  'Serious: demanding or characterized by careful consideration or application',
  'Summary: a brief statement or account of the main points of something',
  'Readily: without hesitation or reluctance; easily or quickly',
  'Service: the action of helping or doing work for someone',
  'Support: to give assistance, encouragement, or approval to someone',
  'Reading: the action or skill of interpreting written or printed matter',
  'Serving: the action of providing food and drink at a meal or event',
  'Suppose: to assume or presume to be the case',
  'Reality: the state of things as they actually exist',
  'Session: a period devoted to a particular activity',
  'Supreme: highest in rank, power, or authority',
  'Realize: to become fully aware of something',
  'Setting: the place or surroundings where something is positioned or where an event takes place',
  'Surface: the outside part or uppermost layer of something',
  'Receipt: a written acknowledgment that something has been received',
  'Seventh: constituting number seven in a sequence',
        'Surgery: the treatment of injuries or disorders of the body by incision or manipulation',
  'Receive: to be given, presented with, or paid (something)',
  'Several: more than two but not many',
  'Surplus: an amount of something left over when requirements have been met; excess',
  'Recover: to return to a normal state of health, mind, or strength',
  'Shortly: in a short time; soon',
  'Survive: to continue to live or exist, especially in spite of danger or hardship',
  'Reflect: to think deeply or carefully about',
  'Showing: displaying or demonstrating something',
  'Suspect: to have an idea or impression of the existence, presence, or truth of (something) without certain proof',
  'Regular: arranged in or constituting a constant or definite pattern, especially with the same space between individual instances',
  'Silence: complete absence of sound',
  'Sustain: to strengthen or support physically or mentally',
  'Related: connected by blood or marriage',
  'Silicon: a chemical element with the symbol Si and atomic number 14',
  'Teacher: a person who teaches, especially in a school',
  'Release: to set free, let go, or allow to escape',
  'Similar: having a resemblance in appearance, character, or quantity, without being identical',
  'Telecom: the transmission of signals, images, sounds, or data by wire, radio, or other electronic or electromagnetic systems',
  'Remains: the parts left over after other parts have been removed, used, or destroyed',
  'Sitting: the action or position of sitting',
  'Telling: having a striking or revealing effect; significant',
      ];
      
      
      
      
        function generate2RandomWords() {
          const randomIndex = Math.floor(Math.random() * twoLetters.length);
          const random2Word = twoLetters[randomIndex];
          document.getElementById('resultContainer').textContent = random2Word;
            }
      
      function generate3RandomWords() {
        const randomIndex = Math.floor(Math.random() * threeLetters.length);
        const random3Word = threeLetters[randomIndex];
           document.getElementById('resultContainer').textContent = random3Word;
            }
      
      function generate4RandomWords() {
        const randomIndex = Math.floor(Math.random() * fourLetters.length);
        const random4Word = fourLetters[randomIndex];
        document.getElementById('resultContainer').textContent = random4Word;
      }
      
      function generate5RandomWords() {
        const randomIndex = Math.floor(Math.random() * fiveLetters.length );
        const random5Word = fiveLetters[randomIndex];
        document.getElementById('resultContainer').textContent = random5Word;
      }

      function generate6RandomWords() {
        const randomIndex = Math.floor(Math.random() * sixLetters.length);
        const random6Word = sixLetters[randomIndex];
        document.getElementById('resultContainer').textContent = random6Word;
      }

      function generate7RandomWords() {
        const randomIndex = Math.floor(Math.random() * sevenLetters.length);
        const random7Word = sevenLetters[randomIndex];
        document.getElementById('resultContainer').textContent = random7Word;



      }
      
      
            const Word2Button = document.getElementById('Word2Button');
            const Word3Button = document.getElementById('Word3Button');
            const Word4Button = document.getElementById('Word4Button');
             const Word5Button = document.getElementById('Word5Button');
             const Word6Button = document.getElementById('Word6Button');
             const Word7Button = document.getElementById('Word7Button');
      
            Word2Button.addEventListener('click', generate2RandomWords);
            Word3Button.addEventListener('click', generate3RandomWords);
            Word4Button.addEventListener('click', generate4RandomWords);
             Word5Button.addEventListener('click', generate5RandomWords);
             Word6Button.addEventListener('click', generate6RandomWords);
            Word7Button.addEventListener('click', generate7RandomWords);
          
      const checkerss = /Blow/;
      console.log(checkerss.test(fourLetters));
      
   
